/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  RunScriptResult,
  DeployContractExecutionResult,
  NetworkId,
} from "@alephium/web3";
import {
  C4factory,
  C4factoryInstance,
  C4Template,
  C4TemplateInstance,
} from ".";
import { default as devnetDeployments } from "....deployments.deployments.devnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    C4factory: DeployContractExecutionResult<C4factoryInstance>;
    C4Template: DeployContractExecutionResult<C4TemplateInstance>;
  };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    C4factory: {
      ...json.contracts["C4factory"],
      contractInstance: C4factory.at(
        json.contracts["C4factory"].contractInstance.address
      ),
    },
    C4Template: {
      ...json.contracts["C4Template"],
      contractInstance: C4Template.at(
        json.contracts["C4Template"].contractInstance.address
      ),
    },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments = networkId === "devnet" ? devnetDeployments : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments: any[] = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
