/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as CreateC4GameScriptJson } from "../CreateC4Game.ral.json";

export const CreateC4Game = new ExecutableScript<{
  factoryId: HexString;
  player1: Address;
  betAmount: bigint;
  player2: Address;
  winner: Address;
  isFinished: boolean;
}>(Script.fromJson(CreateC4GameScriptJson, "", []), getContractByCodeHash);
